use_frameworks!
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
platform :ios, '8.3'
target 'FirebaseClient_Example' do
  pod 'FirebaseClient', :path => '../'
  pod 'GoogleSignIn'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  #pod 'Firebase/Analytics'
  
  target 'FirebaseClient_Tests' do
    inherit! :search_paths

    
  end
end
